name: create-tw-list
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        config: '.markdownlint-cli2.yaml'
        fix: true
        globs: |
          2024-participants/interested-technical-writers/*.md
          !2024-participants/interested-technical-writers/EXAMPLE.md
