name: create-tw-list
on:
  pull_request_target:
    types: [opened]
    paths: 2024-participants/interested-technical-writers/
jobs:
  lint:
    name: lint-pr
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        config: '.markdownlint-cli2.yaml'
        fix: true
        globs: |
          2024-participants/interested-technical-writers/*.md
          !2024-participants/interested-technical-writers/EXAMPLE.md
  comment:
    name: comment-failed
    if: failure()
    uses: peter-evans/create-or-update-comment@v4
    with:
          issue-number: ${{tojson(github.event.number)}}
          body: |
            Your file is not valid Markdown.
