name: create markdown file

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
        contents: write
    steps:
      - uses: actions/checkout@v4
      - run: ls -tr 2024-participants/interested-technical-writers > 2024-participants/interested-technical-writers/input.txt  
      - run: comm -23 <(sort 2024-participants/interested-technical-writers/input.txt) <(sort 2024-participants/interested-technical-writers/remove.txt) >2024-participants/interested-technical-writers/clean-input.txt
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=2024-participants/interested-technical-writers/interested-technical-writers.md
            2024-participants/interested-technical-writers/clean-input.txt
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: Apply php-cs-fixer changes